name: CI

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  link-check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: "docs"
          config-file: ".github/mlc-config.json"
